site_name: Лабораторные работы по веб-программированию
site_description: Документация по лабораторным работам
site_author: Коваленко Евгений

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - search.suggest
    - search.highlight
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: teal
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: teal
      accent: lime

nav:
  - Главная: index.md
  - Лабораторная работа 1:
    - Описание: lr1/index.md
    - Задание 1: lr1/1.md
    - Задание 2: lr1/2.md
    - Задание 3: lr1/3.md
    - Задание 4: lr1/4.md
    - Задание 5: lr1/5.md

markdown_extensions:
  - admonition
  - codehilite
  - extra
  - toc:
      permalink: true
